module.exports = [
    "Drink a glass of water first thing in the morning to kickstart hydration",
    "Take a 5-minute movement break every hour when working at a desk",
    "Chew your food 20-30 times per bite for better digestion",
    "Practice the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds",
    "Eat a rainbow of colorful fruits and vegetables daily",
    "Try standing on one leg while brushing teeth to improve balance",
    "Replace processed snacks with raw nuts and seeds",
    "Sing loudly for 5 minutes daily to boost lung capacity",
    "Use stairs instead of elevators whenever possible",
    "Massage your scalp for 3 minutes to improve circulation",
    "Soak feet in warm water with Epsom salt before bed",
    "Practice deep belly breathing for 2 minutes when stressed",
    "Keep a gratitude journal by your bedside",
    "Rotate your pillowcase every 3 days for better skin health",
    "Spend 10 minutes in sunlight without sunscreen daily",
    "Try writing with your non-dominant hand to stimulate brain activity",
    "Hum while cooking - it naturally slows down eating pace",
    "Keep fresh herbs on your desk for aromatherapy benefits",
    "Do wall push-ups while waiting for coffee to brew",
    "Store phone at eye level to improve posture during use",
    "Squeeze a stress ball during conference calls",
    "Add chia seeds to your morning beverage for omega-3s",
    "Laugh out loud for 1 minute daily - even if forced",
    "Use blue-light blocking glasses after sunset",
    "Practice balancing a book on your head while walking",
    "Alternate hot and cold water in your final shower minute",
    "Trace the alphabet with your toes while sitting",
    "Replace afternoon coffee with green tea",
    "Stretch like a cat when waking up",
    "Count backwards from 100 by 7s to boost mental math",
    "Hug someone (or yourself) for 20 seconds daily",
    "Pretend to chew when smelling food to control portions",
    "Walk backwards for 30 steps to challenge coordination",
    "Write with scented pens to engage multiple senses",
    "Balance your spoon on your nose after eating",
    "Try eating with chopsticks to slow down meals",
    "Make your bed immediately after waking",
    "Alternate nostrils when breathing during meditation",
    "Brush teeth with your opposite hand",
    "Do calf raises while washing dishes",
    "Count colors in your meal before eating",
    "Dance wildly to one song each morning",
    "Practice fake smiling until it becomes real",
    "Squat while waiting for the microwave",
    "Blow bubbles to practice deep breathing",
    "Trace mandalas with your finger during breaks",
    "Alternate sitting positions every 30 minutes",
    "Visualize success before important tasks",
    "Name five things you can hear when anxious",
    "Pretend you're a flamingo while standing in line",
    "End showers with 10 seconds of cold water"
];